server:
  port: 9024

spring:
  kafka:
    bootstrap-servers: localhost:9092

    streams:
      application-id: approval-stream-app
      properties:
        processing.guarantee: exactly_once_v2
        commit.interval.ms: 100
        #default.key.serde: org.apache.kafka.common.serialization.Serdes$StringSerde
        #default.value.serde: org.apache.kafka.common.serialization.Serdes$StringSerde
        default.deserialization.exception.handler: >
          org.apache.kafka.streams.errors.LogAndContinueExceptionHandler

app:
  topics:
    registration-topic: demo-user-registrations
    approval-topic: demo-approval-status  
    approval-group: approval-group

logging:
  level:
    root: INFO                
    com.yusufrh: DEBUG        
    org.apache.kafka: WARN    
    org.apache.zookeeper: WARN
    io.netty: WARN            
    reactor.netty: WARN       
    org.springframework.web: WARN
  pattern:
    console: "%clr(%d{yyyy-MM-dd HH:mm:ss}){faint} %clr(%5p) %clr(---){faint} %clr([%15.15t]){faint} %clr(%-40.40logger{39}){cyan} %clr(:){faint} %m%n%wEx"